add_test([=[ArcReplacerTest.SampleTest]=]  /home/bustub/build/test/arc_replacer_test [==[--gtest_filter=ArcReplacerTest.DISABLED_SampleTest]==] --gtest_also_run_disabled_tests [==[--gtest_output=xml:/home/bustub/build/test/arc_replacer_test.xml]==] [==[--gtest_catch_exceptions=0]==])
set_tests_properties([=[ArcReplacerTest.SampleTest]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[ArcReplacerTest.SampleTest]=]  PROPERTIES WORKING_DIRECTORY /home/bustub/build/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 120)
add_test([=[ArcReplacerTest.SampleTest2]=]  /home/bustub/build/test/arc_replacer_test [==[--gtest_filter=ArcReplacerTest.DISABLED_SampleTest2]==] --gtest_also_run_disabled_tests [==[--gtest_output=xml:/home/bustub/build/test/arc_replacer_test.xml]==] [==[--gtest_catch_exceptions=0]==])
set_tests_properties([=[ArcReplacerTest.SampleTest2]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[ArcReplacerTest.SampleTest2]=]  PROPERTIES WORKING_DIRECTORY /home/bustub/build/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 120)
add_test([=[ArcReplacerTest.RemoveBehaviorTest]=]  /home/bustub/build/test/arc_replacer_test [==[--gtest_filter=ArcReplacerTest.DISABLED_RemoveBehaviorTest]==] --gtest_also_run_disabled_tests [==[--gtest_output=xml:/home/bustub/build/test/arc_replacer_test.xml]==] [==[--gtest_catch_exceptions=0]==])
set_tests_properties([=[ArcReplacerTest.RemoveBehaviorTest]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[ArcReplacerTest.RemoveBehaviorTest]=]  PROPERTIES WORKING_DIRECTORY /home/bustub/build/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] TIMEOUT 120)
set(  arc_replacer_test_TESTS ArcReplacerTest.SampleTest ArcReplacerTest.SampleTest2 ArcReplacerTest.RemoveBehaviorTest)
