if(EXISTS "/home/bustub/build/test/count_min_sketch_test[1]_tests.cmake")
  include("/home/bustub/build/test/count_min_sketch_test[1]_tests.cmake")
else()
  add_test(count_min_sketch_test_NOT_BUILT count_min_sketch_test_NOT_BUILT)
endif()
