
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:8 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:8 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Users/25984/.codex/tmp/arg0/codex-arg0p4SEJA/"
      - "D:/Microsoft VS Code/"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.10.7-hotspot/bin/"
      - "E:/vmware/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Git/cmd/"
      - "D:/Cangjie/bin/"
      - "D:/Cangjie/tools/bin/"
      - "D:/Cangjie/tools/lib/"
      - "D:/Cangjie/runtime/lib/windows_x86_64_llvm/"
      - "C:/Windows/System32/config/systemprofile/.cjpm/bin/"
      - "D:/CodeArts IDE for Cangjie/bin/"
      - "C:/Program Files/MiKTeX/miktex/bin/x64/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "D:/Trae CN/bin/"
      - "D:/cursor/resources/app/codeBin/"
      - "C:/Users/25984/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/25984/AppData/Local/Programs/Windsurf/bin/"
      - "D:/PyCharm 2025.2.2/bin/"
      - "D:/Microsoft VS Code/bin/"
      - "C:/Users/25984/AppData/Roaming/npm/"
      - "C:/Users/25984/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/Scripts/"
      - "D:/cursor/resources/app/bin/"
      - "C:/Users/25984/.vscode/extensions/openai.chatgpt-26.5311.21342-win32-x64/bin/windows-x86_64/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Users/25984/.codex/tmp/arg0/codex-arg0p4SEJA/mingw32-make.exe.com"
      - "C:/Users/25984/.codex/tmp/arg0/codex-arg0p4SEJA/mingw32-make.exe"
      - "D:/Microsoft VS Code/mingw32-make.exe.com"
      - "D:/Microsoft VS Code/mingw32-make.exe"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.10.7-hotspot/bin/mingw32-make.exe.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.10.7-hotspot/bin/mingw32-make.exe"
      - "E:/vmware/bin/mingw32-make.exe.com"
      - "E:/vmware/bin/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "D:/Cangjie/bin/mingw32-make.exe.com"
      - "D:/Cangjie/bin/mingw32-make.exe"
      - "D:/Cangjie/tools/bin/mingw32-make.exe.com"
      - "D:/Cangjie/tools/bin/mingw32-make.exe"
      - "D:/Cangjie/tools/lib/mingw32-make.exe.com"
      - "D:/Cangjie/tools/lib/mingw32-make.exe"
      - "D:/Cangjie/runtime/lib/windows_x86_64_llvm/mingw32-make.exe.com"
      - "D:/Cangjie/runtime/lib/windows_x86_64_llvm/mingw32-make.exe"
      - "C:/Windows/System32/config/systemprofile/.cjpm/bin/mingw32-make.exe.com"
      - "C:/Windows/System32/config/systemprofile/.cjpm/bin/mingw32-make.exe"
      - "D:/CodeArts IDE for Cangjie/bin/mingw32-make.exe.com"
      - "D:/CodeArts IDE for Cangjie/bin/mingw32-make.exe"
      - "C:/Program Files/MiKTeX/miktex/bin/x64/mingw32-make.exe.com"
      - "C:/Program Files/MiKTeX/miktex/bin/x64/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe.com"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe"
      - "D:/Trae CN/bin/mingw32-make.exe.com"
      - "D:/Trae CN/bin/mingw32-make.exe"
      - "D:/cursor/resources/app/codeBin/mingw32-make.exe.com"
      - "D:/cursor/resources/app/codeBin/mingw32-make.exe"
      - "C:/Users/25984/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/25984/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/25984/AppData/Local/Programs/Windsurf/bin/mingw32-make.exe.com"
      - "C:/Users/25984/AppData/Local/Programs/Windsurf/bin/mingw32-make.exe"
      - "D:/PyCharm 2025.2.2/bin/mingw32-make.exe.com"
      - "D:/PyCharm 2025.2.2/bin/mingw32-make.exe"
      - "D:/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "D:/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/25984/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/25984/AppData/Roaming/npm/mingw32-make.exe"
      - "C:/Users/25984/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/Scripts/mingw32-make.exe.com"
      - "C:/Users/25984/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/Scripts/mingw32-make.exe"
      - "D:/cursor/resources/app/bin/mingw32-make.exe.com"
      - "D:/cursor/resources/app/bin/mingw32-make.exe"
      - "C:/Users/25984/.vscode/extensions/openai.chatgpt-26.5311.21342-win32-x64/bin/windows-x86_64/mingw32-make.exe.com"
      - "C:/Users/25984/.vscode/extensions/openai.chatgpt-26.5311.21342-win32-x64/bin/windows-x86_64/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\25984\\.codex\\tmp\\arg0\\codex-arg0p4SEJA"
        - "D:\\Microsoft VS Code"
        - "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.10.7-hotspot\\bin"
        - "E:\\vmware\\bin\\"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Git\\cmd"
        - "D:\\Cangjie\\bin"
        - "D:\\Cangjie\\tools\\bin"
        - "D:\\Cangjie\\tools\\lib"
        - "D:\\Cangjie\\runtime\\lib\\windows_x86_64_llvm"
        - "C:\\WINDOWS\\system32\\config\\systemprofile\\.cjpm\\bin"
        - "D:\\CodeArts IDE for Cangjie\\bin"
        - "C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "d:\\Trae CN\\bin"
        - "d:\\cursor\\resources\\app\\codeBin"
        - "C:\\Users\\25984\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\25984\\AppData\\Local\\Programs\\Windsurf\\bin"
        - "D:\\PyCharm 2025.2.2\\bin"
        - "D:\\Microsoft VS Code\\bin"
        - "C:\\Users\\25984\\AppData\\Roaming\\npm"
        - "C:\\Users\\25984\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\Scripts"
        - "C:\\Users\\25984\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\Scripts"
        - "D:\\cursor\\resources\\app\\bin"
        - "c:\\Users\\25984\\.vscode\\extensions\\openai.chatgpt-26.5311.21342-win32-x64\\bin\\windows-x86_64"
...
