if(EXISTS "D:/my project/bustub/build.codex/test/arc_replacer_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/arc_replacer_test[1]_tests.cmake")
else()
  add_test(arc_replacer_test_NOT_BUILT arc_replacer_test_NOT_BUILT)
endif()
