if(EXISTS "D:/my project/bustub/build.codex/test/binder_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/binder_test[1]_tests.cmake")
else()
  add_test(binder_test_NOT_BUILT binder_test_NOT_BUILT)
endif()
