if(EXISTS "D:/my project/bustub/build.codex/test/buffer_pool_manager_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/buffer_pool_manager_test[1]_tests.cmake")
else()
  add_test(buffer_pool_manager_test_NOT_BUILT buffer_pool_manager_test_NOT_BUILT)
endif()
