if(EXISTS "D:/my project/bustub/build.codex/test/crash_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/crash_test[1]_tests.cmake")
else()
  add_test(crash_test_NOT_BUILT crash_test_NOT_BUILT)
endif()
