if(EXISTS "D:/my project/bustub/build.codex/test/hash_table_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/hash_table_test[1]_tests.cmake")
else()
  add_test(hash_table_test_NOT_BUILT hash_table_test_NOT_BUILT)
endif()
