if(EXISTS "D:/my project/bustub/build.codex/test/rwlatch_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/rwlatch_test[1]_tests.cmake")
else()
  add_test(rwlatch_test_NOT_BUILT rwlatch_test_NOT_BUILT)
endif()
