if(EXISTS "D:/my project/bustub/build.codex/test/skiplist_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/skiplist_test[1]_tests.cmake")
else()
  add_test(skiplist_test_NOT_BUILT skiplist_test_NOT_BUILT)
endif()
