if(EXISTS "D:/my project/bustub/build.codex/test/txn_scan_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/txn_scan_test[1]_tests.cmake")
else()
  add_test(txn_scan_test_NOT_BUILT txn_scan_test_NOT_BUILT)
endif()
