if(EXISTS "D:/my project/bustub/build.codex/test/type_test[1]_tests.cmake")
  include("D:/my project/bustub/build.codex/test/type_test[1]_tests.cmake")
else()
  add_test(type_test_NOT_BUILT type_test_NOT_BUILT)
endif()
