if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/arc_replacer_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/arc_replacer_test[1]_tests.cmake")
else()
  add_test(arc_replacer_test_NOT_BUILT arc_replacer_test_NOT_BUILT)
endif()
