if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/binder_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/binder_test[1]_tests.cmake")
else()
  add_test(binder_test_NOT_BUILT binder_test_NOT_BUILT)
endif()
