if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/clock_replacer_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/clock_replacer_test[1]_tests.cmake")
else()
  add_test(clock_replacer_test_NOT_BUILT clock_replacer_test_NOT_BUILT)
endif()
