if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/crash_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/crash_test[1]_tests.cmake")
else()
  add_test(crash_test_NOT_BUILT crash_test_NOT_BUILT)
endif()
