if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/disk_scheduler_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/disk_scheduler_test[1]_tests.cmake")
else()
  add_test(disk_scheduler_test_NOT_BUILT disk_scheduler_test_NOT_BUILT)
endif()
