if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/hyperloglog_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/hyperloglog_test[1]_tests.cmake")
else()
  add_test(hyperloglog_test_NOT_BUILT hyperloglog_test_NOT_BUILT)
endif()
