if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/lru_replacer_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/lru_replacer_test[1]_tests.cmake")
else()
  add_test(lru_replacer_test_NOT_BUILT lru_replacer_test_NOT_BUILT)
endif()
