if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/page_guard_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/page_guard_test[1]_tests.cmake")
else()
  add_test(page_guard_test_NOT_BUILT page_guard_test_NOT_BUILT)
endif()
