if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/rwlatch_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/rwlatch_test[1]_tests.cmake")
else()
  add_test(rwlatch_test_NOT_BUILT rwlatch_test_NOT_BUILT)
endif()
