if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/trie_debug_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/trie_debug_test[1]_tests.cmake")
else()
  add_test(trie_debug_test_NOT_BUILT trie_debug_test_NOT_BUILT)
endif()
