if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/tuple_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/tuple_test[1]_tests.cmake")
else()
  add_test(tuple_test_NOT_BUILT tuple_test_NOT_BUILT)
endif()
