if(EXISTS "/mnt/d/my project/bustub/build.wsl.perf/test/txn_executor_test[1]_tests.cmake")
  include("/mnt/d/my project/bustub/build.wsl.perf/test/txn_executor_test[1]_tests.cmake")
else()
  add_test(txn_executor_test_NOT_BUILT txn_executor_test_NOT_BUILT)
endif()
